services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: fox
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"