CREATE USER fox WITH SUPERUSER CREATEDB CREATEROLE PASSWORD 'password';
CREATE DATABASE school;
GRANT ALL PRIVILEGES ON SCHEMA public TO fox;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fox;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fox;
