DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'fox') THEN EXECUTE 'CREATE USER fox WITH SUPERUSER CREATEDB CREATEROLE PASSWORD ''password'''; END IF; END $$ LANGUAGE plpgsql;
GRANT ALL PRIVILEGES ON SCHEMA public TO fox;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fox;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fox;